global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090'] # Prom scraping itself (container name)
  - job_name: 'ingest'
    static_configs:
      - targets: ['ingest:8080'] # Using service name instead of localhost to point Prom at the container DNS names on the Compose network
  - job_name: 'worker'
    static_configs:
      - targets: ['worker:8082'] # Using service name instead of localhost to point Prom at the container DNS names on the Compose network