global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - hh-alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alert-rules.yaml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['hh-prometheus:9090'] # Prom scraping itself (container name)
  - job_name: 'ingest'
    static_configs:
      - targets: ['hh-ingest:8080'] # Using service name instead of localhost to point Prom at the container DNS names on the Compose network
  - job_name: 'worker'
    static_configs:
      - targets: ['docker-worker-1:8083', 'docker-worker-2:8083', 'docker-worker-3:8083'] # All worker replicas
  - job_name: 'nsq-monitor'
    static_configs:
      - targets: ['hh-nsq-monitor:8084'] # NSQ monitoring service