apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-ingest" (include "harborhook.fullname" .) }}
  labels:
    app.kubernetes.io/name: {{ include "harborhook.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: ingest
    helm.sh/chart: {{ include "harborhook.chart" . }}
    {{- if .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    {{- end }}
spec:
  replicas: {{ .Values.ingest.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "harborhook.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: ingest
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.ingest.service.httpPort }}"
        prometheus.io/path: "/metrics"
      labels:
        app.kubernetes.io/name: {{ include "harborhook.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: ingest
    spec:
      serviceAccountName: {{ include "harborhook.serviceAccountName" . }}
      containers:
        - name: ingest
          image: "{{ .Values.ingest.image.repository }}:{{ .Values.ingest.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.ingest.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.ingest.service.httpPort }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.ingest.service.grpcPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ printf "%s-ingest-config" (include "harborhook.fullname" .) }}
          volumeMounts:
            - name: certs
              mountPath: /etc/certs
              readOnly: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: certs
          secret:
            secretName: {{ .Values.ingest.certsSecretName | default (printf "%s-certs" (include "harborhook.fullname" .)) }}
