apiVersion: v1
kind: Service
metadata:
  name: {{ include "harborhook.fullname" . }}-jwks-server
  labels:
    {{- include "harborhook.labels" . | nindent 4 }}
    app.kubernetes.io/component: jwks-server
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.jwksServer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "harborhook.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: jwks-server
