apiVersion: v1
kind: Service
metadata:
  name: nsq-monitor
  labels:
    app: nsq-monitor
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.nsqMonitor.service.httpPort }}
      targetPort: http
  selector:
    app: nsq-monitor