apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "harborhook.fullname" . }}-worker-config
  labels:
    {{- include "harborhook.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
data:
  APP_NAME: "worker"
  OTEL_SERVICE_NAME: "harborhook-worker"
  HTTP_PORT: ":{{ .Values.worker.service.httpPort }}"
  GRPC_PORT: ":50052" # Internal port, not exposed via service
  MAX_ATTEMPTS: {{ .Values.worker.maxAttempts | quote }}
  BACKOFF_SCHEDULE: {{ .Values.worker.backoffSchedule | quote }}
  BACKOFF_JITTER_PCT: {{ .Values.worker.backoffJitterPct | quote }}
  PUBLISH_DLQ_TOPIC: {{ .Values.config.nsq.dlqTopic | quote }}
  WORKER_CONCURRENCY: {{ .Values.worker.concurrency | quote }}
  HTTP_CLIENT_TIMEOUT: {{ .Values.worker.httpClientTimeout | quote }}
  DB_USER: {{ .Values.config.db.user | quote }}
  DB_PASS: {{ .Values.config.db.pass | quote }}
  DB_HOST: {{ printf "%s-postgres" .Release.Name | quote }}
  DB_PORT: {{ .Values.config.db.port | quote }}
  DB_NAME: {{ .Values.config.db.name | quote }}
  DB_CONN_MAX_LIFETIME: "1h"
  DB_MAX_IDLE_CONNS: "5"
  DB_MAX_OPEN_CONNS: "10"
  JWT_ISSUER: "harborhook"
  JWT_AUDIENCE: "harborhook-api"
  ENABLE_TLS: "false"
  NSQD_TCP_ADDR: {{ .Release.Name }}-nsqd:4150
  NSQ_LOOKUP_HTTP_ADDR: {{ .Release.Name }}-nsqlookupd:4161
  NSQ_DELIVERIES_TOPIC: {{ .Values.config.nsq.deliveriesTopic | quote }}
  NSQ_DLQ_TOPIC: {{ .Values.config.nsq.dlqTopic | quote }}
  NSQ_WORKER_CHANNEL: {{ .Values.config.nsq.workerChannel | quote }}
  WEBHOOK_SIGNATURE_HEADER: {{ .Values.config.webhook.signatureHeader | quote }}
  WEBHOOK_TIMESTAMP_HEADER: {{ .Values.config.webhook.timestampHeader | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.config.otel.endpoint | quote }}
