apiVersion: v2
name: harborhook
description: A Helm chart for Harborhook, the multi-tenant webhook delivery system.
# application | library
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
- name: postgresql
  version: "18.1.8"
  repository: "https://charts.bitnami.com/bitnami"
  alias: postgres # To match our service name convention
- name: nsq
  version: "0.0.11"
  repository: "https://nsqio.github.io/helm-chart"
  alias: nsq # To match our service name convention

# Observability stack
- name: prometheus
  version: "25.30.0"
  repository: "https://prometheus-community.github.io/helm-charts"
  condition: observability.prometheus.enabled
- name: grafana
  version: "10.1.4"
  repository: "https://grafana.github.io/helm-charts"
  condition: observability.grafana.enabled
- name: loki
  version: "6.46.0"
  repository: "https://grafana.github.io/helm-charts"
  condition: observability.loki.enabled
- name: tempo
  version: "1.24.0"
  repository: "https://grafana.github.io/helm-charts"
  condition: observability.tempo.enabled
- name: promtail
  version: "6.17.1"
  repository: "https://grafana.github.io/helm-charts"
  condition: observability.promtail.enabled